### PR TITLE
Search bar

### LINKED ISSUE #12: Remove metric in the contract/token/wallet details

### LINKED ISSUE #13: Remove Go to Explorer when i am already in the explorer page
We still show the `go to explorer` button even when the user is on the explorer.

### LINKED ISSUE #14: Replace `Your Gateway to Digital Assets!` with `Egabee`
Since users can search transactions and contracts which are not assets the title is misleading.

### LINKED ISSUE #15: Add a link to the top bar go to Egabee Dashboard

### PR DESCRIPTION
**Pull request by zeyad-belal**
edits for the site header and detail pages 
Resolves #12
Resolves #13
Resolves #14
Resolves #15

### CODE REVIEW

**Comment by MuhammedMohsenn** [comment]
when i click `go to dashboard` button, the app crashes because im not authorized, so maybe make the button leads to `Egabee` landing page, or maybe the `login` page so the user login directly.

**Comment by metmirr** [comment]
Can we fix the button style? 

image

**Comment by zeyad-belal** [comment]
> when i click `go to dashboard` button, the app crashes because im not authorized, so maybe make the button leads to `Egabee` landing page, or maybe the `login` page so the user login directly.

yeb i notice that i was going to make an edit for thee context to prevent this crash but i guess it is much eaiser to nav to login if the user logged he will just be navigated to the dashboard ! thanks 🙏

**Comment by zeyad-belal** [comment]
> Can we fix the button style?
> 
> image

fixed

**Review by Nada-orban — APPROVED** [review]

**Review by MuhammedMohsenn — APPROVED** [review]

**Review by MuhammedMohsenn — APPROVED** [review]

**Review by metmirr — APPROVED** [review]
Great work!

**Pull request merged**
